// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjkGbNl9L5Wi2gIQvV9rtdjr6or2Vrm7Q',
    appId: '1:1006992790698:web:328b594a95bcc609cbecd3',
    messagingSenderId: '1006992790698',
    projectId: 'd0mi-712',
    authDomain: 'd0mi-712.firebaseapp.com',
    storageBucket: 'd0mi-712.appspot.com',
    measurementId: 'G-1GXB7JSKR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbVBi-H2VmiiyqwKDEKp1_Zc6V4IvXe3g',
    appId: '1:1006992790698:android:8e646a66f9e11ce8cbecd3',
    messagingSenderId: '1006992790698',
    projectId: 'd0mi-712',
    storageBucket: 'd0mi-712.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRBZxmTPtCoWoVnu_9jqUP27KmkTTzTew',
    appId: '1:1006992790698:ios:748c78966ef09373cbecd3',
    messagingSenderId: '1006992790698',
    projectId: 'd0mi-712',
    storageBucket: 'd0mi-712.appspot.com',
    iosBundleId: 'com.fx712.d0mi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRBZxmTPtCoWoVnu_9jqUP27KmkTTzTew',
    appId: '1:1006992790698:ios:9fb28ad0ad5c9663cbecd3',
    messagingSenderId: '1006992790698',
    projectId: 'd0mi-712',
    storageBucket: 'd0mi-712.appspot.com',
    iosBundleId: 'com.fx712.d0mi.RunnerTests',
  );
}
